[project]
name = "kuredhorn"
version = "0.0.5"
description = ""
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Gui Martins", email = "gmartins@fancywhale.ca" },
]
license = { text = "MIT" }
dependencies = [
    "kubernetes>=36.0.2,<37",
]

[dependency-groups]
dev = [
    "monkeytype>=23.3.0,<24",
    "pytest>=9.0.3,<10",
]

[tool.pytest.ini_options]
testpaths = ["tests"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
